name: Assign default project to issues

on:
  issues:
    types:
    - opened

jobs:
  vulnerability_scan:
    name: Assign relevant issues to Enable project board
    runs-on: ubuntu-latest

    steps:
    - name: Add issue to project
      if: contains(github.event.issue.labels.*.name, 'bug') || contains(github.event.issue.labels.*.name, 'enhancement')
      uses: RasaHQ/create-or-update-project-card@9cce0e7

      with:
        project-number: 1
        column-name: Inbox
        skip-update: true
